### ISSUE TITLE
Labels are not colored in box plot.

### ISSUE THREAD

**Issue by Sunhill666** [Deci-AI/data-gradients#235]
### 🐛 Describe the bug

# My Code

```python3
from data_gradients.managers.detection_manager import DetectionAnalysisManager
from data_gradients.datasets.detection import YoloFormatDetectionDataset

train_data = YoloFormatDetectionDataset(...)
val_data = YoloFormatDetectionDataset(...)
class_names = [...]

analyzer = DetectionAnalysisManager(
    report_title="DeepAquaContinuous",
    config_path="detection.yaml",
    train_data=train_data,
    val_data=val_data,
    class_names=class_names,
    remove_plots_after_report=False,
)

analyzer.run()
```

# Config File

```yaml
report_sections:
  - name: Image Features
    features:
      - SummaryStats
      - ImagesResolution
      - ImageColorDistribution
      - ImagesAverageBrightness
  - name: Object Detection Features
    features:
      - DetectionSampleVisualization:
          n_rows: 2
          n_cols: 3
          stack_splits_vertically: True
      - DetectionClassHeatmap:
          n_rows: 12
          n_cols: 3
          heatmap_shape: [200, 200]
      - DetectionBoundingBoxArea:
          topk: 35
          prioritization_mode: train_val_diff
      - DetectionBoundingBoxPerImageCount
      - DetectionBoundingBoxSize
      - DetectionClassFrequency:
          topk: 35
          prioritization_mode: train_val_diff
      - DetectionClassesPerImageCount:
          topk: 35
          prioritization_mode: train_val_diff
      - DetectionBoundingBoxIoU:
          num_bins: 10
          class_agnostic: true
      - DetectionResizeImpact:
          resizing_sizes:
            - [64, 64]
            - [96, 96]
            - [128, 128]
            - [160, 160]
            - [192, 192]
            - [224, 224]
            - [256, 256]
            - [320, 320]
            - [384, 384]
            - [448, 448]
            - [512, 512]
            - [640, 640]
            - [768, 768]
            - [896, 896]
            - [1024, 1024]
          area_thresholds: [1,4,9,16,64]
```

# Output

The box plot is outputted uncolored.
![DetectionBoundingBoxArea](https://github.com/user-attachments/assets/0a685437-a199-4e25-afc4-619ae4f7a20e)

### Versions

Collecting environment information...
PyTorch version: 2.4.0
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
Clang version: Could not collect
CMake version: version 3.29.5
Libc version: glibc-2.35

Python version: 3.11.10 (main, Oct  3 2024, 07:29:13) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.8.0-48-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.4.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 550.107.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.0.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        39 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               20
On-line CPU(s) list:                  0-19
Vendor ID:                            GenuineIntel
Model name:                           13th Gen Intel(R) Core(TM) i5-13600KF
CPU family:                           6
Model:                                183
Thread(s) per core:                   2
Core(s) per socket:                   14
Socket(s):                            1
Stepping:                             1
CPU max MHz:                          5100.0000
CPU min MHz:                          800.0000
BogoMIPS:                             6988.80
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect user_shstk avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi vnmi umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize arch_lbr ibt flush_l1d arch_capabilities
Virtualization:                       VT-x
L1d cache:                            544 KiB (14 instances)
L1i cache:                            704 KiB (14 instances)
L2 cache:                             20 MiB (8 instances)
L3 cache:                             24 MiB (1 instance)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-19
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Mitigation; Clear Register File
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Enhanced / Automatic IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS SW sequence; BHI BHI_DIS_S
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] numpy==2.0.1
[pip3] torch==2.4.0
[pip3] torchaudio==2.4.0
[pip3] torchvision==0.19.0
[pip3] triton==3.0.0
[conda] blas                      1.0                         mkl    defaults
[conda] cuda-cudart               12.4.127                      0    nvidia
[conda] cuda-cupti                12.4.127                      0    nvidia
[conda] cuda-libraries            12.4.0                        0    nvidia
[conda] cuda-nvrtc                12.4.127                      0    nvidia
[conda] cuda-nvtx                 12.4.127                      0    nvidia
[conda] cuda-opencl               12.6.77                       0    nvidia
[conda] cuda-runtime              12.4.0                        0    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] libcublas                 12.4.2.65                     0    nvidia
[conda] libcufft                  11.2.0.44                     0    nvidia
[conda] libcurand                 10.3.7.77                     0    nvidia
[conda] libcusolver               11.6.0.99                     0    nvidia
[conda] libcusparse               12.3.0.142                    0    nvidia
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] libnvjitlink              12.4.99                       0    nvidia
[conda] mkl                       2023.1.0         h213fc3f_46344    defaults
[conda] mkl-service               2.4.0           py311h5eee18b_1    defaults
[conda] mkl_fft                   1.3.10          py311h5eee18b_0    defaults
[conda] mkl_random                1.2.7           py311ha02d727_0    defaults
[conda] numpy                     2.0.1           py311h08b1b3b_1    defaults
[conda] numpy-base                2.0.1           py311hf175353_1    defaults
[conda] pytorch                   2.4.0           py3.11_cuda12.4_cudnn9.1.0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] pytorch-cuda              12.4                 hc786d27_6    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] pytorch-mutex             1.0                        cuda    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torchaudio                2.4.0               py311_cu124    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torchtriton               3.0.0                     py311    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torchvision               0.19.0              py311_cu124    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
